### ISSUE TITLE
linting freezes

### ISSUE THREAD

**Issue by heijligers** [Agentic-Insights/codebase-context-spec#12]
### Discussed in https://github.com/Agentic-Insights/codebase-context-spec/discussions/11

<div type='discussions-op-text'>

<sup>Originally posted by **heijligers** September 11, 2024</sup>
I've just had aider create a context document and after installing ran the linter.

![CleanShot 2024-09-11 at 19 32 30@2x](https://github.com/user-attachments/assets/59ad7c2e-0a08-482c-a925-2789f0a62f17)

Now the program seems to just have frozen</div>

**Comment by killerapp** [comment]
I believe this has bee fixed in 1.4.2, could you retest?
