### ISSUE TITLE
Example of Codebase Context Spec with Cody

### ISSUE THREAD

**Issue by wvanheemstra** [Agentic-Insights/codebase-context-spec#6]
**Is your feature request related to a problem? Please describe.**
To get started with Codebase Context Spec, I would appreciate an example with [Cody](https://sourcegraph.com/cody).

**Describe the solution you'd like**
A step by step guide that explains by example how to use Codebase Context Spec with Cody.

**Describe alternatives you've considered**
Alternatively, other AI Coding Assistants could be examplified.

**Additional context**
As there are no examples yet, no resources are as of yet available that could be used as template.

**Comment by killerapp** [comment]
take a look at:

CODING-ASSISTANT-PROMPT.md in the root, also review this project, it has several examples in the root and in the typescript linter folder.

You can add these types of files to your repo and then use a prompt similar to the above. 

I am not familiar with Cody, it might be the only coding assistant that I haven't tried yet.
Could you try this and see how it works for you?

**Comment by wvanheemstra** [comment]
I copy the text from CODING-ASSISTANT-PROMPT.md and create a prompt with this for Cody. If I ask Cody to use the .context.md file in the root of the repository as additional input, it returns with indeed a very nice summary of all the information provided in the .context.md file. It thus describes my repository correctly as intended, i.e. by echoing the details specified in the .context.md file. Thanks @killerapp for this wonderful tool! Conclusion: Cody is already supported.

**Comment by killerapp** [comment]
Awesome, but I would love for you to reach out to the author and ask them to support the other aspects of the convention with tooling, specifically, the `.contextdocs.md` sytem and `.contextignore`
